Added Scipy implementation for simpson
ubsuny/CP1-24-HW7 pull request #22
Opened 2024-11-21 02:49 UTC by Priyanka-43

For this assignment all pull requests going  forward should contain the following (please delete the placeholder text and add your own description)

# Title
  - A ledgible title that briefly describes the contents of the pull request.

## Linting
  - Does your code lint? If not are the errors within acceptable errors?

## Contents
  - A legible description that indepthly describes the contents of the pull request.
  - A list of files that are new / changed
  - The contents that you have been assigned to submit labeled with titles that acuratly describe the assignment they are for

## Labels and Milestones
  - ALL pull requests must have an attached label and Milestone before a reviewer can be assigned.

## Reviewer
  - add a sugggested reviewer here (perhaps your team mate)

Any further questions on formatting pull requests can be asked in the issues tab or on discord. 
This document can be changed at any time.

2024-11-21 04:06 UTC, Priyanka-43 commented
Hi, i am unable to fix my pytest error. I tried a lot. Can anyone help me in this?

2024-11-21 04:26 UTC, zbpetersbuf commented
Yes this is because you are not doing a pytest test function, this defining class and if __name__ == "__main__": is specifically what @laserlab said not to do a couple weeks ago in class, I suggest looking at other peoples test functions

2024-11-21 04:29 UTC, Priyanka-43 commented
@zbpetersbuf  previously i was doing the same like not to use  name == "main", But it was still showing error. I will do one commit more to see.

2024-11-21 04:33 UTC, zbpetersbuf commented
also the class TestCalculusFunctions(unittest.TestCase):, this is not pytest, pytest does not recognize this as a test function please look at other peoples test functions

2024-11-21 04:34 UTC, Priyanka-43 commented
Ok sure.

2024-11-21 04:36 UTC, zbpetersbuf commented
ill check in the morning to merge after an approved review

2024-11-21 06:01 UTC, Priyanka-43 commented
Hi, I have tried different codes to run. There is always error in  scipy. Not giving correct result. If i am running in jupyter NB, it is giving result.

2024-11-21 14:18 UTC, zbpetersbuf commented
Result: 99.0000020612203
=========================== short test summary info ============================
FAILED test_calculus.py::test_scipy_simpson - AssertionError: Expected 2.0, but got 99.0000020612203
assert np.False_

maybe the best way to fix this is to trouble shoot on your end, by making sure before you use np.isclose is actually close on the range you give it before making it into a test_function

2024-11-21 16:12 UTC, laserlab commented on test_calculus.py
> +from calculus import scipy_simpson
DO not make a second import statement of the same module, which is not even used

2024-11-21 16:13 UTC, laserlab requested changes
- doubled import statement
- repo has to be synced

2024-11-21 23:53 UTC, Priyanka-43 commented
Can anyone help me to resolve my pytest error? I have done correct implementation.

2024-11-22 02:47 UTC, zbpetersbuf commented
@Priyanka-43 lines 35 and 36 why are you printing f"x and f"y this would only be in debugging or when you are making the code, if its in your pull request you should know it works, have you tried removing these? perhaps this is why your test function is failing

2024-11-22 02:50 UTC, zbpetersbuf commented
the function will be printing numbers and returning values but in the test function you are comparing it to just your retuned variables and not the print statement

2024-11-22 02:51 UTC, Priyanka-43 commented
@zbpetersbuf Before that also it was failing, i was trying different things to see if this somehow get resolved. But if you say i will remove those lines. Because i am not able to find mistake.

2024-11-22 02:55 UTC, Priyanka-43 commented
I have removed those lines, still showing error.

2024-11-22 04:28 UTC, zbpetersbuf commented
@Priyanka-43 ok so now the error is Expected 2, but got 63.6619775813128 this is good 
this means that the function is outputting an expected type of data, its just that the numbers don't match, this is possible due to either the function or test function giving an incorrect output, try different numbers or test functions
perhaps in your module have print statements (you will have to delete these before the pull request is accepted) to see what's going wrong on your end
my honest advise is try @laserlab office
if not that its then to copy your function you are testing and your test function aswell as your pytest issue (found after pressing the blue details on the right) into chat got and see if that helps you

2024-11-22 15:26 UTC, laserlab commented
> @Priyanka-43 ok so now the error is Expected 2, but got 63.6619775813128 this is good this means that the function is outputting an expected type of data, its just that the numbers don't match, this is possible due to either the function or test function giving an incorrect output, try different numbers or test functions perhaps in your module have print statements (you will have to delete these before the pull request is accepted) to see what's going wrong on your end my honest advise is try @laserlab office if not that its then to copy your function you are testing and your test function aswell as your pytest issue (found after pressing the blue details on the right) into chat got and see if that helps you

Good case why unit testing is useful. The computer does what you tell it to do and that is you return scipy.simpson of the array you give it. If you read scipy documentation you will read:

```python
Parameters
    ----------
    y : array_like
        Array to be integrated.
    x : array_like, optional
        If given, the points at which `y` is sampled.
    dx : float, optional
        Spacing of integration points along axis of `x`. Only used when
        `x` is None. Default is 1.
    axis : int, optional
        Axis along which to integrate. Default is the last axis.
```
Which gives you the answer what is wrong.

2024-11-23 01:38 UTC, Priyanka-43 commented
@zbpetersbuf Hi, I have made the required changes. All pylint and pytest are working. If you can merge this pull request.

2024-11-23 15:50 UTC, zbpetersbuf commented
@Priyanka-43 you must still resolve conflicts before I am able to merge it

2024-11-23 16:04 UTC, Priyanka-43 commented
@zbpetersbuf I have done that.

2024-11-23 18:20 UTC, merged