Adaptive Trapezoid C++ implementation
ubsuny/CP1-24-HW7 pull request #44
Opened 2024-11-25 09:39 UTC by abruns123

## Linting
 The python code should lint

## Contents
Added c++ implementation of the adaptive trapezoid integration to the c++ calculus file. 
Also added pytest for that and adjusted wrapper implementation of adaptive trapezoid to take 
in general functions. 

## Labels and Milestones

## Reviewer
kylemas917 is recommended to review

2024-11-25 15:51 UTC, kylemasc917 commented on calculus.py
> -
Why are these functions being deleted?

2024-11-25 15:59 UTC, kylemasc917 commented on test_calculus.py
> +    result1=lib.adapt_c(python_cubic_c, -1,1,10,10)
I believe the pytest is failing here because above we've imported the functions as calc so this is missing the calc. before adapt_c

2024-11-25 16:10 UTC, kylemasc917 commented on calculus.py
> -
the undefined pylint errors come from you still using d1,2,3 below but deleting them above. Can be fixed by not deleting them.

2024-11-25 16:14 UTC, kylemasc917 commented
Other pylint errors are just some unused imports, some missing docstrings and lines too long, and the deleted functions in calc.py not existing so in testcalc.py when they are called it can't call them.

2024-11-25 16:16 UTC, kylemasc917 requested changes
the code itself you were assigned looks good and runs well, but there are a few changes made to the existing files that are strange and cause a number of errors that can be fixed by not removing certain preexisting functions. Also removing everybody else's functions from the file would cause a number of homework issues and be a real bummer. Once these are addressed, I'll approve, and they can be merged.

2024-11-25 19:08 UTC, abruns123 commented
Okay, I fixed all pylint/pytest errors. I adjusted my implementation of the wrapper function such that it took in a different parameter type and some of the other functions I made with it became irrelevant. Those were deleted and I adjusted one of the pytests to use the correct parameters. No functions that were deleted were ones I didn't make. I fixed they pytest error with the c_adapt by using calculus. and updating the calculus.dll file via the terminal.

2024-11-25 19:36 UTC, kylemasc917 commented
Ah ok for some reason the files changed view was showing something crazy but it looks good now. you just have to resolve the merge conflicts

2024-11-25 22:02 UTC, abruns123 commented
okay, merge conflicts should be resolved now

2024-11-25 23:59 UTC, kylemasc917 approved these changes
Everything looks good. Approved!

2024-11-26 00:00 UTC, kylemasc917 commented
@zbpetersbuf good to go!

2024-11-26 00:21 UTC, zbpetersbuf approved these changes

2024-11-26 00:21 UTC, merged